spring:
  application:
    name: spring-cloud-config-server-crystalbudget
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/Earl/CrystalBudget/Spring/local-repo-crystalbudget
          default-label: main
server:
  port: 8888


#77777
